site_name: MixTape - Tutorial
theme: 
    name: bootswatch
    name: lumen
nav: 
  - Overview: 'index.md'
  - Tutorial: 
    - Intro to Web APIs: 'web-apis-intro.md'
    - Authentication: 'requests-auth.md'
    - Getting Data: 'requests-get-data.md'
    - Replit Database: 'replit-database.md'
    - Flask Web Apps: 'flask-jinja-templates.md'
    - Customizing Mixtape: 'customizing-mixtape.md'
    - Completed Example: 'completed-example.md'
    - Next Steps: 'next-steps.md'
    
  

markdown_extensions:
  - toc:
        toc_depth: 2-6
  - admonition
  - attr_list

plugins: []
extra_css: [extra.css]